In [35]:
import numpy as np
import pandas as pd
a = np.arange(10)**3

In [3]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [4]:
a[:6:2] = 1000

In [5]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [9]:
a[:6:3]**1/3

array([333.33333333,   9.        ])

In [10]:
1:3

SyntaxError: illegal target for annotation (673777854.py, line 1)

In [13]:
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[1:3]

array([1, 2])

In [23]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])

In [24]:
x['a'].shape

(2, 2)

In [25]:
x['a'].dtype

dtype('int32')

In [26]:
x['b'].shape

(2, 2, 3, 3)

In [27]:
x['b'].dtype

dtype('float64')

In [29]:
x['a']

array([[0, 0],
       [0, 0]], dtype=int32)

In [30]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [31]:
x['b'][1,1,1] = 1

In [32]:
x['a']

array([[0, 0],
       [0, 0]], dtype=int32)

In [33]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [1., 1., 1.],
         [0., 0., 0.]]]])

In [34]:
np.float_

numpy.float64

In [40]:
rng = pd.date_range("1/1/2012", periods=100, freq="S")

rng

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 00:00:01',
               '2012-01-01 00:00:02', '2012-01-01 00:00:03',
               '2012-01-01 00:00:04', '2012-01-01 00:00:05',
               '2012-01-01 00:00:06', '2012-01-01 00:00:07',
               '2012-01-01 00:00:08', '2012-01-01 00:00:09',
               '2012-01-01 00:00:10', '2012-01-01 00:00:11',
               '2012-01-01 00:00:12', '2012-01-01 00:00:13',
               '2012-01-01 00:00:14', '2012-01-01 00:00:15',
               '2012-01-01 00:00:16', '2012-01-01 00:00:17',
               '2012-01-01 00:00:18', '2012-01-01 00:00:19',
               '2012-01-01 00:00:20', '2012-01-01 00:00:21',
               '2012-01-01 00:00:22', '2012-01-01 00:00:23',
               '2012-01-01 00:00:24', '2012-01-01 00:00:25',
               '2012-01-01 00:00:26', '2012-01-01 00:00:27',
               '2012-01-01 00:00:28', '2012-01-01 00:00:29',
               '2012-01-01 00:00:30', '2012-01-01 00:00:31',
               '2012-01-

In [41]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

ts

2012-01-01 00:00:00    315
2012-01-01 00:00:01    144
2012-01-01 00:00:02     74
2012-01-01 00:00:03    323
2012-01-01 00:00:04    155
                      ... 
2012-01-01 00:01:35      6
2012-01-01 00:01:36    197
2012-01-01 00:01:37    404
2012-01-01 00:01:38    196
2012-01-01 00:01:39    185
Freq: S, Length: 100, dtype: int64

In [42]:
ts.resample("5Min").sum()

2012-01-01    22427
Freq: 5T, dtype: int64

In [43]:
ts.sum()

22427

In [44]:
ts.resample("5Min")

In [50]:
pd.Series(ts.resample("5S"))

0      (2012-01-01 00:00:00, [315, 144, 74, 323, 155])
1     (2012-01-01 00:00:05, [226, 175, 372, 438, 167])
2      (2012-01-01 00:00:10, [117, 347, 363, 256, 35])
3        (2012-01-01 00:00:15, [71, 471, 34, 27, 180])
4      (2012-01-01 00:00:20, [217, 33, 179, 253, 113])
5      (2012-01-01 00:00:25, [163, 35, 105, 134, 242])
6       (2012-01-01 00:00:30, [38, 343, 374, 60, 285])
7      (2012-01-01 00:00:35, [146, 492, 361, 353, 47])
8      (2012-01-01 00:00:40, [42, 200, 331, 317, 343])
9        (2012-01-01 00:00:45, [62, 131, 5, 383, 409])
10    (2012-01-01 00:00:50, [352, 320, 372, 439, 424])
11        (2012-01-01 00:00:55, [5, 85, 221, 415, 51])
12     (2012-01-01 00:01:00, [481, 316, 29, 169, 415])
13      (2012-01-01 00:01:05, [107, 420, 99, 140, 46])
14       (2012-01-01 00:01:10, [2, 453, 197, 95, 297])
15     (2012-01-01 00:01:15, [485, 238, 19, 387, 116])
16    (2012-01-01 00:01:20, [144, 293, 101, 201, 297])
17    (2012-01-01 00:01:25, [348, 334, 211, 261, 451])
18      (2